ekf_local:
  ros__parameters:
    frequency: 20.0
    publish_tf: true
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    twist0: /vehicle/ground_speed
    twist0_config: [false, false, false, # x, y, z
                    false, false, false, # roll, pitch, yaw
                    true, true, false,  # vx, vy, vz
                    false, false, true]  # vroll, vpitch, vyaw
    twist0_queue_size: 5

    # Outlier-Handling (Mahalanobis-Gate)
    twist0_rejection_threshold: 3.5   # 3–5 ist üblich
